### PR TITLE
Trying to merge with sha2 branch of your OpenSC.tokend repo

### PR DESCRIPTION
**Pull request by mouse07410**
I don't think Sha2 branch got any better testing that my own fork ("master"), mainly because I was the main tester of this stuff, both for your change, and for my changes (and unsurprisingly, my changes got exercised more).

Also, at the PR creation time, it does not tell me why it "can't automatically merge"...

Anyway, you asked for a PR against your sha2 branch - here it is.

### CODE REVIEW

**Comment by frankmorgner** [comment]
It could not be merged because there is a merge conflict, that I hoped you could resolve.

Anyway, one last time I have fixed that in https://github.com/OpenSC/OpenSC.tokend/pull/21. Please note that _your_ git history is a mess:
- commits don't build up on each other (your history is effectively broken)
- if you want to merge some change you should clean the commits by avoiding distracting temporary fixups
- you should try to separate each change into a single commit.

Before you continue developing I'd advice you to do a hard reset of your master branch to OpenSC/OpenSC.tokend master and to create a temporary developement branch which holds the changes of frankmorgner/OpenSC.tokend sha2

Regarding the code, I found two new questions:
The outlook workarounds actually includes two cases:

```
if ((context.algorithm() == CSSM_ALGID_ECDSA
                && mKey.signKey()->type == SC_PKCS15_TYPE_PRKEY_RSA)
            || (context.algorithm() == CSSM_ALGID_RSA
                && mKey.signKey()->type == SC_PKCS15_TYPE_PRKEY_EC))
```

which is the correct one (it's the only one that should be included in the patch)?

Second, there now is

```
//flags |= SC_ALGORITHM_RSA_PAD_PKCS1; // hopefully not needed now
```

Which changes the previous logic for RSA. Did you actually test this with RSA? I _don't_ hink it can be omitted.

**Comment by mouse07410** [comment]
> The outlook workarounds actually includes two cases: ......

It is not a work-around - it's a safety catch. It intercepts attempts that are guaranteed to result in a bad signature due to key type not matching the requested algorithm. Therefore both are needed. I personally observed Outlook to issuing RSA signature request for EC keys. That doesn't mean we shouldn't check for the other possibility - a bad-behaving application asking for ECDSA signature using RSA key.

> Second, there now is ......

The thing is - the code just before it sets `flags` to PADDING_NONE, then checks if it is RSA in which case it sets the padding to PKCS1. The line you're asking for is a duplicate of that operation, therefore unnecessary. But see below:

> Did you actually test this with RSA? I don't think it can be omitted.

It looks like you are right - it signs fine, but somehow the signature fails to verify...

**Comment by frankmorgner** [comment]
We can only _work around_ Outlook's mistake, for other programs the "safety catch" should return an error instead of trying to be sophisticated. I'll add this to my branch.

`flags` is different from `padding`. `flags` must be initialized so that the lower layer knows the actual padding.

**Comment by frankmorgner** [comment]
Wait a second, I thought you wanted to silently fix Outlook's behaviour, instead I just saw that you're only throwing an error. This, of course, is OK, but didn't you say that you fixed this already?

**Comment by mouse07410** [comment]
1. You were right - I got back to the code, and found that the line you were asking about is still necessary. It must be there. We cannot comment it out. Good catch, thanks!
2. I want to silently fix Outlook behavior where I can. I absolutely want to catch error and stop the code from generating assuredly bad signatures. I fixed the Outlook for RSA keys - it works fine (well-tested). I have not succeeded yet with Outlook and EC keys. Therefore the only thing I can do now is catching the error before a corrupted signature is generated. What I tried so far, allowed Outlook to generate signatures with EC keys, but they were not verifiable. So I'm willing to let it be for now, and just catch an illegal attempts (key type mismatches). I'm quite happy to get SHA-2 support in, and on top of that to get ECDSA support that any "normal" email client (e.g., Apple Mail - tested and working) can use. Sorry, my work-around for Outlook is not ready yet. :-( 

> Please note that your git history is a mess

I'm afraid I have to agree. 

> you should try to separate each change into a single commit

Will do so in the future.

> I'd advice you to do a hard reset of your master branch to OpenSC/OpenSC.tokend master
> and to create a temporary developement branch which holds the changes of
> frankmorgner/OpenSC.tokend sha2

I probably _do_ need a hard reset of my master branch. But I question the choice of resetting it to OpenSC/OpenSC.tokend - because that's an ancient non-working never-updated version. The only good thing I know about it is that it compiles on 10.10+. This makes me rather concerned regarding cloning from it.

Your sha2 branch - it's not even integrated with your master, correct?

**Comment by frankmorgner** [comment]
funny fact, I found two more critical problems, I already pushed everything to https://github.com/OpenSC/OpenSC.tokend/pull/21. Unfortunately I cannot test or build right now...

**Pull request merged**
