### PR TITLE
Fix compilation problems, and removed an undefined hash 

### PR DESCRIPTION
**Pull request by mouse07410**
@frankmorgner I suggest that this fix is better for several reasons:
1. It sets the correct signature length (I'm not sure that `sc_pkcs15_compute_signature()` returns the length of the output data).
2. It removes SC_ALGORITHM_ECDSA_HASH_MD5 which has not been defined (I think MD5 has been prohibited by the time ECDSA came about).

### CODE REVIEW

**Comment by frankmorgner** [comment]
thanks, I rewrote the commits applying these changes. However, it's strange that tokend used to work with using the result from `sc_pkcs15_compute_signature` (which should be `SC_SUCCESS` or `0`), see https://github.com/OpenSC/OpenSC.tokend/blob/master/OpenSC/OpenSCKeyHandle.cpp#L149

**Comment by mouse07410** [comment]
@frankmorgner we've diverged again (can't merge with your sha2 branch) in the last 2 hours.

Do you want me to even provide code and PR's? Or should I just maintain my fork to the best I can, and report bugs? For there doesn't seem to be a point to provide PR's if you're going to re-do them anyway.

Also, is there a way to generate a PR against a commit (given by 6-digit hex number)? I seem to be able to generate a PR only against branches of your (or my) repo...

Also, do you have any plans to merge these changes to master? (I'm not asking about the main OpenSC.tokend repo, because that one is beyond hope - but frankmorgner/OpenSC.tokend master should be within reach?)

**Comment by frankmorgner** [comment]
Well, you asked me to remove one of my commits which would have required rewriting my git history anyway (destroying any incoming PR).

To keep pace, simply create new branches (no need to resolve conflicts for the old ones). Fetch my remote, checkout my branch sha2 to a new local branch, apply your changes, make a PR. Branches are cheap in git(hub)! You may still keep "your" version lying around in some other branch.

**Comment by mouse07410** [comment]
Well, OpenSC.tokend stopped working - it locks and unlocks fine, but it lost the ability to sign with RSA keys. Haven't tried EC keys yet. Here's what it looks like:
screen shot 2015-12-03 at 00 07 29

It's been quite a while since I've had this problem with RSA signatures/

**Comment by mouse07410** [comment]
OK. I've reverted my fork back to your old https://github.com/mouse07410/OpenSC.tokend/commit/ccf55b7c6dcca33735905af8f1305a49f7c78d60, added a bit of correction with my https://github.com/mouse07410/OpenSC.tokend/commit/806f7c3fdb1ea901bfc37efc74b65868950c4322 (in my repo fork, master branch). With that both RSA and ECDSA signatures work again.

Feel free to take a look at my fork, or figure why yours stopped working. As far as I'm concerned, RSA and ECDSA signatures are done, and don't need any changes. 

In the meanwhile I hope to collaborate with @dengert to maybe figure what parameters we can feed to `pkcs15_derive()` to get ECDH working.

**Comment by frankmorgner** [comment]
Hmm, I can't reproduce this. SSL authentication works as expected for me, but that may have different parameters than iMail. One substantial difference I see, is that the original code forces PKCS1 padding for RSA (the actual padding is requested, but the result is ignored). Could you try forcing PKCS1 padding and set debug to 20 and see what happens?

**Comment by mouse07410** [comment]
Sorry, I'm at the older (working) code level now, and don't have time to dive into this. Also afraid to mess my git repo again, I've already had too much trouble with it.

And your new code does not seem to get beyond the entrance to the `generateRsaSignature()`. I've sprayed it with a ton of debugging messages, none of which was printed - except for the one that was the very first executable statement in the body of that method. So it does not look like the padding code was executed. The log after the first "entering generateRsaSignature()" message was filled with ton of record sequences line this, and nothing more:

```
0x7fff70f99300 02:08:51.581 [tokend] /Users/uri/src/OpenSC/OpenSC.tokend/OpenSC/OpenSCRecord.cpp:85:getAcl: In OpenSCCertificateRecord::getAcl, tag is: (null)
0x7fff70f99300 02:08:51.581 [tokend] /Users/uri/src/OpenSC/OpenSC.tokend/OpenSC/OpenSCRecord.cpp:95:getAcl:   returned 1 ACL entries
```

I plan to concentrate on encryption/decryption, unless a new problem surfaces in the current (what you'd call "old") signature code.

**Comment by frankmorgner** [comment]
OK, then I hope you find time to refactor the code as done in https://github.com/frankmorgner/OpenSC.tokend/commit/696bacfc068ac60731aba1761d072ff107fa3d0c

**Comment by mouse07410** [comment]
> OK, then I hope you find time to refactor the code as done in 696bacf

May I ask why? Refactored code might look a bit better (though it's a matter of taste), but it does not work. So why bother with refactoring something that works (and looks reasonably OK if you ask me) into something that doesn't (and thus would require uncertain amount of work to whip into shape)??? Especially when there are other burning issues/problems?

**Comment by frankmorgner** [comment]
I am not aware that someone asked for ECC or sha2 support in tokend in the last 20 years.

The real problem is maintainability. That's why we need clean code and clear commits.

Am 3. Dezember 2015 16:20:16 MEZ, schrieb Mouse notifications@github.com:

> > OK, then I hope you find time to refactor the code as done in 696bacf
> 
> May I ask why? Refactored code might look a bit better (though it's a
> matter of taste), but it does not work. So why bother with
> refactoring??? Especially when there are other burning issues/problems?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/frankmorgner/OpenSC.tokend/pull/4#issuecomment-161672780

## 

Frank Morgner

**Comment by mouse07410** [comment]
Nobody seemed to have asked for PIV support in tokend either. 

And one correction: your new code does not work with SHA1 either. I suspect it also broke MD5, but have no means to verify it.

**Pull request closed without merging**
