### PR TITLE
Add fixes/support for SHA-2

### PR DESCRIPTION
**Pull request by mouse07410**
1. Added support for ECC keys.
2. Added support for SHA-2 in signatures.
3. Added support (incomplete) for ECC decryption/key-wrap.
4. Increased number of objects (in all likelihood unnecessary, but shouldn't hurt either).

### CODE REVIEW

**Comment by mouse07410** [comment]
And it would be nice if these fixes could be propagated to the mainstream OpenSC.tokend (though I'm not holding my breath for that).

**Comment by frankmorgner** [comment]
please use tabs instead of spaces for indenting.

the changes in README.md are not meant to be for OpenSC.tokend

**Comment by frankmorgner** [comment]
I had to make quite a lot of changes, see https://github.com/frankmorgner/OpenSC.tokend/commit/b78fc32133e99bbd503e9bb42fce5b80d41a051f. Could you check if it still works for you?

One more question: In https://github.com/frankmorgner/OpenSC.tokend/commit/b78fc32133e99bbd503e9bb42fce5b80d41a051f#diff-6ce0f18a3ba98851e309d687b2128399R88 we are checking for `CSSM_ALGID_ECDSA`, but in https://github.com/frankmorgner/OpenSC.tokend/commit/b78fc32133e99bbd503e9bb42fce5b80d41a051f#diff-6ce0f18a3ba98851e309d687b2128399R213 we are checking for `CSSM_ALGID_ECDH`. Which one is right?

**Comment by mouse07410** [comment]
> I had to make quite a lot of changes, see b78fc32.

My apologies - making you do extra work was not intentional.

> Could you check if it still works for you?

I will try to test https://github.com/frankmorgner/OpenSC.tokend/commit/b78fc32133e99bbd503e9bb42fce5b80d41a051f and report. Looking at it, I think it should be merged.

Yes both `CSSM_ALGID_ECDSA` and `CSSM_ALGID_ECDH` are correct - because they cover different areas: S/MIME Signature and S/MIME Encryption.

When we deal with _signature_, we add support for ECDSA - so we check for `CSSM_ALGID_ECDSA` in addition to the already-supported RSA-based signatures. When we deal with _encryption_, we need to wrap/unwrap the symmetric key using ECC algorithm - ECDH (or EC El Gamal). So both need to be there, and in their respective places (**not** interchangeable!).

**Comment by frankmorgner** [comment]
You did the hard work, no problem!

Thanks for clarifying the algorithms. Please post your testing results here https://github.com/OpenSC/OpenSC.tokend/pull/21

**Comment by frankmorgner** [comment]
Sorry, I can't merge your new changes with https://github.com/frankmorgner/OpenSC.tokend/commit/b78fc32133e99bbd503e9bb42fce5b80d41a051f. Could you give me a hand?

By the way, your Outlook hack looks sane, we should keep it.

**Comment by mouse07410** [comment]
> Sorry, I can't merge your new changes with b78fc32. Could you give me a hand?

Why, of course!  What seems to be the problem?

Oh, and perhaps my new/current changes supersede b78fc32, so it isn't necessary any more? I'd say - if there appears to be a conflict between b78fc32 and the current PR, the current PR takes precedence.

I've made my current PR against your fork of OpenSC.tokend, the way it is, without any additional commits. I suspect it subsumes whatever was agreed upon before but hasn't been merged at the time this PR was created.

> By the way, your Outlook hack looks sane, we should keep it.

Thank you. It is incomplete - messages signed by Outlook with this hack arrive with bad signatures. But it's a start...

**Comment by frankmorgner** [comment]
With b78fc32133e99bbd503e9bb42fce5b80d41a051f I cleaned up your initial commits 31f1b485f6bcf52251504c5c02270f123253c20f...211db3b79aecbb33861b0dbb9fa976d368eca270. I was hoping that you would rebase your additional commits 217c0b992938745c0015fe5cdd77c425fd56c475...b78fc32133e99bbd503e9bb42fce5b80d41a051f onto b78fc32133e99bbd503e9bb42fce5b80d41a051f

If Outlook support is _not_ functioning, please _don't_ include your workaround.

**Comment by mouse07410** [comment]
Sorry, I'm not experienced enough to create PRs against code that hasn't been committed. I.e. I can make PR against a repo.

Outlook patch is correct - is throws an error if an RSA operation with EC keys is requested.

Forgetting the prior commits - do you see a problem with this PR? If not - it would be nice to merge it as a current level, so future/subsequent work could base off it. If yes - let's discuss it. But it looks like this PR is doing everything that your proposed commit does, plus addresses more issues.

**Comment by mouse07410** [comment]
Darn... I meant to say: the attempt to enable Outlook signing failed, so the current PR catches the problem and reports it rather than trying to proceed, because we know now that proceeding there would only create a bad signature. This check is a necessary step - you cannot assume all the clients behave correctly because we have at least one (and major) example of a client that doesn't (Outlook).

**Comment by frankmorgner** [comment]
please simply rebase onto b78fc32133e99bbd503e9bb42fce5b80d41a051f, then I'll have a look at what else is to do.

**Comment by mouse07410** [comment]
> please simply rebase onto b78fc32, then I'll have a look at what else is to do.

@frankmorgner , I **don't know** how to rebase onto something like b78fc32 as opposed to rebasing onto a branch (like "master" or such). I **think** you want to rebase onto "sha2" branch of your repo. Here's the PR:
https://github.com/frankmorgner/OpenSC.tokend/pull/3

**Pull request closed without merging**
